layout_spectrum: 0.04200822487473488
typography_spectrum: 0.4147114553488791
color:
  brandStrength: 0.41201169858686626
  lightness: 0.48615433531813323
  saturation: 0.30805404274724424
  rhythmicContrast: 0.17488716379739344
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
author:
  name: Robine Zijderhand
  email: info@robinezijderhand.nl
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54c1c015-a58c-4576-b125-79debf5f85d7.png
name: Robine Zijderhand Kindercoach
title: 'Lessen, Trainingen, Onderwijsarrangementen,  Spel, Leermethoden, Bijeenkomsten'
